name: Managed-Oxygen

on:
  push:
    branches: ['main']
    paths: Managed-Oxygen/**

permissions:
  contents: write
  pull-requests: read

env:
  solution: Managed-Oxygen

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Generate new Version
        id: semver
        uses: weareinspark/semver-from-labels@main
        with:
          prefix: $solution

      - uses: iamkubi/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "${{ env.solution }}/"
          gzip: true
          draft: true
          name: ${{ steps.semver.outputs.newversion }}
          tag: ${{ steps.semver.outputs.newversion }}