name: tag

on:
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: read

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Generate new Version
        id: semver
        uses: weareinspark/semver-from-labels@main
      - run: |
          echo ${{ steps.semver.outputs.newversion }}